[2024-10-07T02:56:22.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T02:56:22.840+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL_JsonData.unzip manual__2024-10-07T02:41:18.296437+00:00 [queued]>
[2024-10-07T02:56:22.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL_JsonData.unzip manual__2024-10-07T02:41:18.296437+00:00 [queued]>
[2024-10-07T02:56:22.851+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-10-07T02:56:22.867+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): unzip> on 2024-10-07 02:41:18.296437+00:00
[2024-10-07T02:56:22.875+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2139) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-07T02:56:22.877+0000] {standard_task_runner.py:63} INFO - Started process 2143 to run task
[2024-10-07T02:56:22.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL_JsonData', 'unzip', 'manual__2024-10-07T02:41:18.296437+00:00', '--job-id', '544', '--raw', '--subdir', 'DAGS_FOLDER/ETLProject/main.py', '--cfg-path', '/tmp/tmp0fr6133p']
[2024-10-07T02:56:22.878+0000] {standard_task_runner.py:91} INFO - Job 544: Subtask unzip
[2024-10-07T02:56:22.928+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL_JsonData.unzip manual__2024-10-07T02:41:18.296437+00:00 [running]> on host ecb02e117702
[2024-10-07T02:56:23.020+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_ETL_JsonData' AIRFLOW_CTX_TASK_ID='unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T02:41:18.296437+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-07T02:41:18.296437+00:00'
[2024-10-07T02:56:23.021+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T02:56:23.033+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-07T02:56:23.034+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'gunzip \\\\wsl.localhost\\Ubuntu\\og_item_impression.20240830_\\og_item_impression.20240830_1130_1.json.gz']
[2024-10-07T02:56:23.047+0000] {subprocess.py:86} INFO - Output:
[2024-10-07T02:56:23.051+0000] {subprocess.py:93} INFO - gzip: \wsl.localhostUbuntuog_item_impression.20240830_og_item_impression.20240830_1130_1.json.gz: No such file or directory
[2024-10-07T02:56:23.052+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-07T02:56:23.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T02:56:23.064+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-07T02:56:23.069+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ETL_JsonData, task_id=unzip, run_id=manual__2024-10-07T02:41:18.296437+00:00, execution_date=20241007T024118, start_date=20241007T025622, end_date=20241007T025623
[2024-10-07T02:56:23.085+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 544 for task unzip (Bash command failed. The command returned a non-zero exit code 1.; 2143)
[2024-10-07T02:56:23.132+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T02:56:23.149+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T02:56:23.152+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
